### ISSUE TITLE
Move `client.create` to `client.containers.create`

### ISSUE THREAD

**Issue by BrunnerLivio** [alandoherty/node-lxd#12]
For the sake of expandability, I recommend moving the `create` method of the `Client`-class to the `Container`-class.

**Proposed Changes**

- `client.create` -> `client.containers.create`
- `client.containers` -> `client.containers.all`
- `client.container` -> `client.containers.get`

- `client.profiles` -> `client.profiles.all`
- `client.profile` -> `client.profiles.get`

**Why?**
In the future there will be more `create`-operations, rather than just for containers. For example "create image". It can be confusing for the user, when calling `client.create`, if he will create an image or a container.

Also, in the `Client`-class does not belong any container, profile or image logic in my opinion. It is a cleaner code, if any "container"-logic is in `Container.js.`

**How?**
Each class is going to need a wrapper. I would call it a Service. 

So  e.g. `client.containers` is an instance of the class `ContainersService`. This class offers CRUD methods of containers.
A small TypeScript example to clarify my intentions
```TypeScript
class ContainerService {
  all(callback: function);
  get(name: string, callback: function);
  delete(container: string|Container, callback: function); 
}
``` 

**Note:**
If this gets accepted, maybe use `create` as an alias for `client.containers.create`, but throw a deprecation warning, so we don't break every application, which upgraded the version.

**Important:**
This would be a breaking change!

**Comment by alandoherty** [comment]
Have to agree, as long as it's a static function referenced in the Client but implemented in `Container.js`. Definitely have to include the alias tho.
