### ISSUE TITLE
How to authenticate with the remote container?

### ISSUE THREAD

**Issue by shark0der** [alandoherty/node-lxd#4]
I'm trying to connect to a remote endpoint but I'm not quite sure how should I authenticate. I'm using this code:

```
var lxd = require('node-lxd');
var client = lxd('hostname:8443');

client.containers(function(e, c) {
  console.log(e, c && c.map(function(i) { return i.name(); }) || 'no containers');
});
```

And I get this error:

```
$ node lxd.js
constructor {
  _message: 'HTTP Error',
  _status: 'Failed',
  _statusCode: 400,
  _innerError: 
   { Error: Parse Error
       at Error (native)
       at Socket.socketOnData (_http_client.js:363:20)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at TCP.onread (net.js:548:20) bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' } } 'no containers'
```

I'm not sure how to debug this. Any ideas?

**Comment by shark0der** [comment]
Ok, so the error is thrown because there's an attempt to communicate using HTTP to an HTTPS endpoint. The next bump I hit was to allow self-signed certificates so I just added `strictSSL: false` in the options object passed to request. The next step seems to be the client authentification because I'm getting a 403 from the server.

**Comment by alandoherty** [comment]
I can't really debug it tonight but the environment variable LXDN_DEV=true will provide verbose per-request logs to the console.

I'll look into tomorrow as I didn't do much testing for remote setups.

**Comment by alandoherty** [comment]
HTTPS was fixed by a recent pull request.
