### ISSUE TITLE
Using GET for creation is an anti-pattern.

### ISSUE THREAD

**Issue by ghost** [alandoherty/node-lxd#9]

**Comment by alandoherty** [comment]
Could you be more specific as to where this pattern is used?

**Comment by ghost** [comment]
https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html
Hmm I don't remember where I found in the code GET for resource creation.

**Comment by ghost** [comment]
Sorry, false alarm. I sent this at 5am, so I guess I worked overnight and was hallucinating from tiredness. :D

**Comment by ghost** [comment]
Hmm I found this in the readme by the expressjs example: `app.get("/create", ...`. Afaik the get method by express is for handling HTTP GET requests. I think both the `/create` and `/run` should be POST even by the express webapp, not just by the REST API, if you don't want to violate the HTTP standard.

**Comment by alandoherty** [comment]
Fixed in README.md

1babf1abad81419e4aa3b061cf1217cf97202133
